### PR TITLE
Pulling in upstream updates to restler

### PR DESCRIPTION
**Pull request by zbirkenbuel**
Not quite to the extent that winston was, but restler has advanced since we forked.  This branch pulls in all of those changes.  Again, probably easier to compare my branch to upstream master which reflects the changes we've made to the codebase:

https://github.com/danwrong/restler/compare/master...HBOCodeLabs:zackb-massive?expand=1

the changes shown effectively reflect what @jstamerj committed to master in the one and only merge: https://github.com/HBOCodeLabs/restler/commit/1a736d2c31afeea49086d652f4c5b2f616022147

### CODE REVIEW

**Comment by zbirkenbuel** [comment]
@jjfeiler @rick-kilgore @allenarthurgay

**Comment by shimeez** [comment]
@jstamerj Wasn't there some bug that caused us to double encode bodies on retries? Was this a fix in restler?

**Comment by zbirkenbuel** [comment]
@shimeez, I'm assuming that's what the move of data from the options blob to the root object was about.  The link to @jstamerj 's merge should show the same changes here.

**Comment by jstamerj** [comment]
@zbirkenbuel @shimeez 
Right -- the problem was with POST requests (or any request with a body).  Restler code would automatically retry some failures, but it would screw up the request body on all the retries.  This once caused ATV to flood the playback marker service with requests.  The initial request would fail for some other reason, and then the retries would repeatedly fail because restler was sending bad data in the request body.

The first time through, the code would convert this.options.data from a string to a buffer.  On retries, it would stringify this buffer (which produces a much different string than the original), and convert that string into a buffer.

I submitted a PR to restler (https://github.com/danwrong/restler/pull/124), but it looks like they did not take the fix.

It looks like they fixed it in a different way 'tho (https://github.com/danwrong/restler/commit/a5901e611060a2abb8fc38788cccaef3752c6ab6), so prehaps we can get rid of our restler fork.

**Comment by zbirkenbuel** [comment]
@jstamerj, yeah, I was just reading through the commit history since there was a merge conflict I resolved in that area.  I does look to be handled, I'd also vote for just pulling from restler at this point instead of our own fork.

**Comment by zbirkenbuel** [comment]
@jstamerj - it looks like they tried to fix it, but not in all of the scenarios we've encountered.  Using just mainline restler we get an error in one of our Newton-Core tests where it tries to retry but adds a very small body where there should be none.  Switching back to this branch seems to work just fine.  This branch breaks some of restler's unit tests, but I can focus on that instead of more changes in Newton.

**Comment by jvaleske** [comment]
Looks good.

**Pull request merged**
